server:
  port: 3573
  ssl:
    enabled: true
    # 로컬
    key-store: keystore.jks
    # 서버용
    #key-store: "classpath:keystore.jks"
    key-store-password: fox990810
    key-alias: tomcat

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: fox990810
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
